#!/bin/bash

## This Script will run only on the first run of the server and run the installer if the admin password is set in an
## environment variable. It can be skipped by setting the enviroment variable $SKIP_INSTALL

if [ -n "$PASSWORD" -a -z "$SKIP_INSTALL" ]; then
    unattendedinstall
fi


if [ -z "$DEBUG_LOGGING" ]; then
  sed -e 's/AsyncLogger name="se.curity" level="DEBUG"/AsyncLogger name="se.curity" level="INFO"/g' "$IDSVR_HOME/etc/log4j2.xml" > "$IDSVR_HOME/etc/log4j2.xml"
fi